import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/_ui/navbar.ui";
import { Hero } from "@/_ui/hero";
import Services from "@/_ui/service.ui";
import Projects from "@/_ui/projects.ui";
import Winners from "@/_ui/winners.ui";
import Footer from "@/_ui/footer";
import Footer_Logo_section from "@/_ui/footer.logo.ui";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <Hero />
        <Services />
        <Projects />
        <Winners />
        <Footer />
        <Footer_Logo_section />
        {/* {children} */}
      </body>
    </html>
  );
}
